name: Bug report
description: Create a bug report to help us improve
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: Write OS information or any related environment info such as IDE.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Contributors should be able to follow the steps provided in order to reproduce the bug.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
